/*Reporter.log():
===============

If you want to log a msg in the Report generated by TestNg , we have to use log(String s) method which is present in Reporter class of TestNg

Reporter.log(String s);
Reporter.log("your msg");

Reporter.log(String s, boolean logToStandardOut)
Reporter.log("your msg",true);--> Console
*/

/*
 priority:
===========
> when ever we have multiple testcase in a TestNG class we can use priority helper attribute
> priority accepts +ve and -ve integer
> by default priority will be Zero.
> if priority is same , again its runs based on Alphabetical order.
*/

package TestNG;

import org.testng.Reporter;
import org.testng.annotations.Test;

public class First_Priority {  // --->TestNG class
	
	
	@Test(priority=1)
	public void executeScript1()  //--->TestCase
	
	{
		
	Reporter.log("TestNG Method1", true);  //--->Test steps;
	}
	
	
	@Test                                    //by default priority will be zero(when priority is not given) (-ve > 0 > +ve)
	public void executeSript2()
	
	{
		Reporter.log("TestNG Method2", true);
	}

	
	@Test(priority=-1)
	public void executeSript3()
	{
		Reporter.log("TestNG Method3", true);
	}

	
	@Test(priority=1)         //if priority is same, again its run on alphabetical order
	public void executeSript4()
	{
		Reporter.log("TestNG Method4", true);
	}

}
